baseURL = 'https://chem1537.ga'
languageCode = 'ru-ru'
title = 'Допы по химии 1537 9л'
theme = 'geekdoc'
defaultContentLanguage = 'ru'
defaultContentLanguageInSubdir = true

[params]
mainSections = ['extra-classes']
